#!/usr/bin/python3
# COMP3311 21T3 Ass2 ... progression check for a given student

import sys
import psycopg2
import re
from helpers import Print_fail, getBasicProgramInfo, getBasicStreamInfo, getCompletedSubjects, getProgramRules, getProgramStreamTableByZid, getStreamRules, getStudent, getProgram, getStream, getNameByZid

# define any local helper functions here
def getRelevantRules(rules, CourseCode, required_type):
	relevant_rules = []
	for rule in rules:
		[rule_name, rule_type, min_req, max_req, courses] = rule
		if rule_type == required_type:
			for course in courses:
				if type(course) == list:
					for course_code in course:
						if re.match(course_code, CourseCode):
							relevant_rules.append(rule_name)
				elif type(course) == str and re.match(course, CourseCode):
					relevant_rules.append(rule_name)
		else:
			continue
	return relevant_rules


### set up some globals
debug = 1



usage = f"Usage: {sys.argv[0]} zID [Program Stream]"
db = None

### process command-line args

argc = len(sys.argv)
if argc < 2:
	print(usage)
	exit(1)
zid = sys.argv[1]
if zid[0] == 'z':
	zid = zid[1:8]
digits = re.compile("^\d{7}$")
if not digits.match(zid):
	print("Invalid student ID")
	exit(1)

progCode = None
strmCode = None

if argc == 4:
	progCode = sys.argv[2]
	strmCode = sys.argv[3]

# manipulate database

try:
	db = psycopg2.connect(dbname="mymyunsw",user="yst990102",password="zxcvb987321",port="6000")
	stuInfo = getStudent(db,zid)
	if not stuInfo:
		print(f"Invalid student id {zid}")
		exit()
	#print(stuInfo)
	[family_name , given_name] = getNameByZid(db, zid)[1:]
	print(f"{zid} {family_name}, {given_name}")

	if progCode:
		progInfo = getProgram(db,progCode)
		if not progInfo:
			print(f"Invalid program code {progCode}")
			exit()

	if strmCode:
		strmInfo = getStream(db,strmCode)
		if not strmInfo:
			print(f"Invalid program code {strmCode}")
			exit()

	# if have a program/stream
	#   show progression check on supplied program/stream
	# else
	#   show progression check on most recent program/stream enrolment

	if progCode and strmCode:
		program = progCode
		stream = strmCode
	else:
		prog_strm_table = getProgramStreamTableByZid(db, zid)
		latest_prog_strm = prog_strm_table[-1]
		program = latest_prog_strm[1]
		stream = latest_prog_strm[2]

	program_name = getBasicProgramInfo(db,program)[1]
	stream_name = getBasicStreamInfo(db, stream)[1]

	if debug : print(f"  {program} {program_name}")
	if debug : print(f"  {stream} {stream_name}")

	# get program rules
	program_rules = getProgramRules(db, program)
	formated_program_rules = []
	for program_rule in program_rules:
		formated_program_rule = list(program_rule)[:-1]

		splited_requirements = program_rule[-1].split(",")
		formated_requirements = []
		for i in splited_requirements:
			i = i.replace('{', '["')
			i = i.replace('}', '"]')
			i = i.replace(';', '","')
			if '[' in i and ']' in i:
				formated_requirements.append(eval(i))
			elif '#' in i:
				formated_requirements.append(re.sub('#', '.', i))
			else:
				formated_requirements.append(i)
  
		formated_program_rule.append(formated_requirements)
		formated_program_rules.append(formated_program_rule)
	program_rules = formated_program_rules

	# get stream rules
	stream_rules = getStreamRules(db, stream)
	formated_stream_rules = []
	for stream_rule in stream_rules:
		formated_stream_rule = list(stream_rule)[:-1]

		splited_requirements = stream_rule[-1].split(",")
		formated_requirements = []
		for i in splited_requirements:
			i = i.replace('{', '["')
			i = i.replace('}', '"]')
			i = i.replace(';', '","')
			if '[' in i and ']' in i:
				formated_requirements.append(eval(i))
			elif '#' in i:
				formated_requirements.append(re.sub('#', '.', i))
			else:
				formated_requirements.append(i)
		formated_stream_rule.append(formated_requirements)
		formated_stream_rules.append(formated_stream_rule)
	stream_rules = formated_stream_rules

	if debug : print(program_rules)
	if debug : print(stream_rules)

	print(f"\nCompleted:")
	CompletedSubjects = getCompletedSubjects(db, zid)
	for CompletedSubject in CompletedSubjects:
		[CourseCode, Term, SubjectTitle, Mark, Grade, UOC] = CompletedSubject
		if Grade in Print_fail:
			print(f"{CourseCode} {Term} {SubjectTitle:<32s}{Mark:>3}   fail does not count")
		else:
			relevant_rules = {}
			relevant_program_rules_DS = getRelevantRules(program_rules, CourseCode, 'DS')
			relevant_program_rules_CC = getRelevantRules(program_rules, CourseCode, 'CC')
			relevant_program_rules_PE = getRelevantRules(program_rules, CourseCode, 'PE')
			relevant_program_rules_FE = getRelevantRules(program_rules, CourseCode, 'FE')
			relevant_program_rules_GE = getRelevantRules(program_rules, CourseCode, 'GE')
			
			relevant_stream_rules_DS = getRelevantRules(stream_rules, CourseCode, 'DS')
			relevant_stream_rules_CC = getRelevantRules(stream_rules, CourseCode, 'CC')
			relevant_stream_rules_PE = getRelevantRules(stream_rules, CourseCode, 'PE')
			relevant_stream_rules_FE = getRelevantRules(stream_rules, CourseCode, 'FE')
			relevant_stream_rules_GE = getRelevantRules(stream_rules, CourseCode, 'GE')

			relevant_rules.update({'DS':relevant_program_rules_DS + relevant_stream_rules_DS})
			relevant_rules.update({'CC':relevant_program_rules_CC + relevant_stream_rules_CC})
			relevant_rules.update({'PE':relevant_program_rules_PE + relevant_stream_rules_PE})
			relevant_rules.update({'FE':relevant_program_rules_FE + relevant_stream_rules_FE})
			relevant_rules.update({'GE':relevant_program_rules_GE + relevant_stream_rules_GE})

			if debug : print(relevant_rules)

			Toward_str = ""
			if relevant_rules['CC']:	Toward_str = " + ".join(sorted(relevant_rules['CC'], reverse=True))
			elif relevant_rules['PE']:	Toward_str = " + ".join(sorted(relevant_rules['PE'], reverse=True))
			elif relevant_rules['FE']:	Toward_str = " + ".join(sorted(relevant_rules['FE'], reverse=True))
			elif relevant_rules['GE']:	Toward_str = " + ".join(sorted(relevant_rules['GE'], reverse=True))

			if debug : print()
			if debug : print(Toward_str)

			# for Toward_rule_name in Toward_str:
			# 	# remove course from program_rules
			# 	for i in len(program_rules):
			# 		if Toward_rule_name == program_rules[i][1]:
			# 			for j in range(program_rules[i][4]):
			# 				if type(program_rules[i][4][j]) == list:
			# 					for k in len(program_rules[i][4][j]):
			# 						if re.match(program_rules[i][4][j][k], CourseCode):
										



except Exception as err:
	print("DB error: ", err)
finally:
	if db:
		db.close()